### PR TITLE
rename unknown-user.png -> DefaultUser.png

### PR DESCRIPTION
**Pull request by un1versal**
I understand you are maintaining Confluence now, this PR fixes the missed bit which is part of https://github.com/xbmc/xbmc/pull/8856

Offtopic: I would like to talk to you on IRC if possible

thx

### CODE REVIEW

**Comment by HitcherUK** [comment]
Thanks for the PR.

PS I don't use IRC but you can PM me on the forum.

**Comment by un1versal** [comment]
fyi main skin in repo is still 3.0.0 so its broken https://github.com/xbmc/repo-skins/tree/krypton

**Comment by un1versal** [comment]
@HitcherUK this change didn't make its way to normal repo where confluence is which means this is broken and not that it matters but the skin in repo is still 3.0.0 https://github.com/xbmc/repo-skins/tree/krypton and that is massively broken in comparison to this and where you forked this from https://github.com/xbmc/skin.confluence which is now 3.0.5

So whats the deal? Are you the maintainer? Is anyone looking after the skin and will anyone make sure all updates make its way to the repo? Its been weeks now just asking since silence makes for poor communication.

**Comment by HitcherUK** [comment]
Sorry, I've got some more changes I need to sort out before I send a request to update it. Now it's not the official skin I have to do this through the mailing list like all other skins.

**Pull request merged**
