### PR TITLE
after #1 use DefaultUser.png instead

### PR DESCRIPTION
**Pull request by un1versal**
small oops, should have done at same time as #1

### CODE REVIEW

**Comment by HitcherUK** [comment]
https://github.com/HitcherUK/skin.confluence/commit/111d3f879d9cadbc2cb2eece7d07dd0044b80c61

**Comment by un1versal** [comment]
?

**Comment by HitcherUK** [comment]
Already done in v3.0.4

**Comment by un1versal** [comment]
its not, look closer

**Pull request merged**
